### ISSUE TITLE
Latest changes need to be published

### ISSUE THREAD

**Issue by aschultz** [emilioicai/react-native-safe-modules#4]
Looks like this was last published a year ago, so none of the RNW changes are available through npm yet.

**Comment by aschultz** [comment]
@jonthysell Any chance you can publish this?

**Comment by aschultz** [comment]
@emilioicai Ping

**Comment by emilioicai** [comment]
sorry for that @aschultz , I will be publishing a new version during the weekend

**Comment by emilioicai** [comment]
v1.0.1 has been published.
